/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file is automatically generated by Next.js.
// It's included here so TypeScript compiles cleanly in a fresh clone.
